//
//  StudentList.swift
//  Classroom
//
//  Created by Samarth Tiwari on 23/08/22.
//

import Foundation

let studentList = [[
    Student(name: "Samarth", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Jayesh", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vaibhav", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anmom", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
],[
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
],[
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
],[
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
],[
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
],[
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Abhinav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Anish", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Utsav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Vardaan", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s"),
]

]
