//
//  StudentList.swift
//  Classroom
//
//  Created by Samarth Tiwari on 23/08/22.
//

import Foundation

let studentList = [[
    Student(name: "Samarth", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 20),
    Student(name: "Jayesh", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 80),
    Student(name: "Vaibhav", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 70),
    Student(name: "Anmom", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 70),
    Student(name: "Abhinav", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 70),
    Student(name: "Anish", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 57),
    Student(name: "Utsav", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 98),
    Student(name: "Vardaan", age: 21, _class: 1, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 45),
],[
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 79),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 79),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 78),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 63),
    Student(name: "Abhinav", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 86),
    Student(name: "Anish", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 98),
    Student(name: "Utsav", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 88),
    Student(name: "Vardaan", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 67),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 86),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 75),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 96),
    Student(name: "Samarth", age: 21, _class: 2, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 65),
],[
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 74),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 46),
    Student(name: "Abhinav", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 37),
    Student(name: "Anish", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 74),
    Student(name: "Utsav", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 65),
    Student(name: "Vardaan", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 66),
    Student(name: "Abhinav", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 55),
    Student(name: "Anish", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 88),
    Student(name: "Utsav", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 44),
    Student(name: "Vardaan", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 77),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 54),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 76),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 87),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 64),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 35),
    Student(name: "Samarth", age: 21, _class: 3, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 56),
],[
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 76),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 45),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 68),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 45),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 68),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 35),
    Student(name: "Abhinav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 68),
    Student(name: "Anish", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 34),
    Student(name: "Utsav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 57),
    Student(name: "Vardaan", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 35),
    Student(name: "Abhinav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 98),
    Student(name: "Anish", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 3),
    Student(name: "Utsav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 98),
    Student(name: "Vardaan", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 65),
    Student(name: "Abhinav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 64),
    Student(name: "Anish", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 53),
    Student(name: "Utsav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 75),
    Student(name: "Vardaan", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 86),
    Student(name: "Abhinav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 97),
    Student(name: "Anish", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 64),
    Student(name: "Utsav", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 75),
    Student(name: "Vardaan", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 73),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 72),
    Student(name: "Samarth", age: 21, _class: 4, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 47),
],[
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks:37),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks:66),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks:94),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks:46),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks:74),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks:34),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks:22),
    Student(name: "Samarth", age: 21, _class: 5, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks:66),
],[
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks:34),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 62),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 65),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 86),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 45),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 24),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 77),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 26),
    Student(name: "Utsav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 84),
    Student(name: "Vardaan", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 37),
    Student(name: "Abhinav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 25),
    Student(name: "Anish", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 74),
    Student(name: "Utsav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 84),
    Student(name: "Vardaan", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 62),
    Student(name: "Abhinav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 73),
    Student(name: "Anish", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 95),
    Student(name: "Utsav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 63),
    Student(name: "Vardaan", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 83),
    Student(name: "Abhinav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 82),
    Student(name: "Anish", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 62),
    Student(name: "Utsav", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 64),
    Student(name: "Vardaan", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 95),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 91),
    Student(name: "Samarth", age: 21, _class: 6, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgcpS7Saw2pX6XZeRzxydcP29EYJh5N7PySC7L4Sg&s", marks: 81),
]

]
